global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'remote_ubuntu_nodes'
    static_configs:
      - targets: ['192.168.0.88:9100', '192.168.0.89:9100', '192.168.0.87:9100', '192.168.0.90:9100', '192.168.0.71:9100']



